2021-11-11 11:51:12,455 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:46]
2021-11-11 11:51:15,792 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_posts().all()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/models.py", line 49, in followed_posts
    return followed.union(own).order_by(Post.timestamp.desc())
AttributeError: type object 'Post' has no attribute 'timestamp'
2021-11-11 11:51:17,515 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_posts().all()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/models.py", line 49, in followed_posts
    return followed.union(own).order_by(Post.timestamp.desc())
AttributeError: type object 'Post' has no attribute 'timestamp'
2021-11-11 11:51:42,260 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_posts().all()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/models.py", line 49, in followed_posts
    return followed.union(own).order_by(Post.timestamp.desc())
AttributeError: type object 'Post' has no attribute 'timestamp'
2021-11-11 11:51:42,750 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_posts().all()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/models.py", line 49, in followed_posts
    return followed.union(own).order_by(Post.timestamp.desc())
AttributeError: type object 'Post' has no attribute 'timestamp'
2021-11-11 11:51:42,915 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_posts().all()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/models.py", line 49, in followed_posts
    return followed.union(own).order_by(Post.timestamp.desc())
AttributeError: type object 'Post' has no attribute 'timestamp'
2021-11-11 11:51:47,071 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 30, in index
    posts = current_user.followed_posts().all()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/models.py", line 49, in followed_posts
    return followed.union(own).order_by(Post.timestamp.desc())
AttributeError: type object 'Post' has no attribute 'timestamp'
2021-11-11 11:54:49,768 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:46]
