2021-11-11 14:32:12,956 ERROR: Exception on / [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 33, in index
    return render_template('index.html', title='Home', form=form,posts=posts)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/base.html", line 38, in top-level template code
    {%  block content %} {% endblock %}
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/index.html", line 21, in block 'content'
    {% include "_post.html" %}
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/_post.html", line 5, in template
    <a href="{{ url_for('user',username=post.author.username)")}}> {{ post.author.username }} </a> says : <b> {{post.body}}</b>
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 173
2021-11-11 14:32:14,311 ERROR: Exception on /explore [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 41, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
AttributeError: 'float' object has no attribute 'desc'
2021-11-11 14:32:15,949 ERROR: Exception on /explore [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 41, in explore
    posts = Post.query.order_by(Post.timestamp.desc()).all()
AttributeError: 'float' object has no attribute 'desc'
2021-11-11 14:32:52,212 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:46]
2021-11-11 14:32:54,512 ERROR: Exception on /explore [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 42, in explore
    return render_template('index.html', title='Explore' , posts=posts)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/base.html", line 38, in top-level template code
    {%  block content %} {% endblock %}
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/index.html", line 21, in block 'content'
    {% include "_post.html" %}
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/templates/_post.html", line 5, in template
    <a href="{{ url_for('user',username=post.author.username)")}}> {{ post.author.username }} </a> says : <b> {{post.body}}</b>
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 173
