2021-11-11 16:25:12,196 ERROR: Exception on /user/ali [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 99, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(page, app.config['POST_PER_PAGE'], False)
AttributeError: 'float' object has no attribute 'desc'
2021-11-11 16:27:56,298 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:46]
2021-11-11 19:40:17,084 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:05:12,131 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:06:25,523 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:07:36,070 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:10:41,362 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:11:03,410 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:11:24,128 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:13:01,145 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:13:37,198 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:14:41,817 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:14:55,952 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:15:05,663 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:17:34,799 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:17:57,539 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:36:14,847 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:37:36,874 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:37:51,934 ERROR: Exception on /logout [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 75, in logout
    logout_user()
NameError: name 'logout_user' is not defined
2021-11-11 21:38:22,599 ERROR: Exception on /logout [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 75, in logout
    logout_user()
NameError: name 'logout_user' is not defined
2021-11-11 21:38:23,197 ERROR: Exception on /logout [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 75, in logout
    logout_user()
NameError: name 'logout_user' is not defined
2021-11-11 21:38:24,010 ERROR: Exception on /logout [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 75, in logout
    logout_user()
NameError: name 'logout_user' is not defined
2021-11-11 21:38:27,417 ERROR: Exception on /logout [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/app/routes.py", line 75, in logout
    logout_user()
NameError: name 'logout_user' is not defined
2021-11-11 21:38:38,365 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:38:56,043 ERROR: Exception on /reset_password_request [GET] [in /Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/Users/hamzaqahosuh/PycharmProjects/microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'reset_password_request' did not return a valid response. The function either returned None or ended without a return statement.
2021-11-11 21:42:47,694 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
2021-11-11 21:43:05,423 INFO: Microblog startup [in /Users/hamzaqahosuh/PycharmProjects/microblog/app/__init__.py:48]
